apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jenkinsci.serviceAccountName" . }}
  namespace: {{ template "jenkinsci.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jenkinsci.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "jenkinsci.serviceAccountName" . }}
    namespace: {{ template "jenkinsci.namespace" . }}