apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "jenkinsci.fullname" . }}
  labels:
    app: {{ template "jenkinsci.fullname" . }}
spec:
  capacity:          
    storage: {{ .Values.persistence.capacity.storage }}
  accessModes:       
    - {{ .Values.persistence.accessModes | quote}}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.storageClassName }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
