apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkinsci.fullname" . }}
  namespace: {{ template "jenkinsci.namespace" . }}
  labels:
    {{- include "jenkinsci.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort}}
      protocol: TCP
      nodePort: {{ .Values.service.http.nodePort }}
      name: {{ .Values.service.http.targetPort }}
    - port: {{ .Values.service.agent.port }}
      targetPort: {{ .Values.service.agent.targetPort }}
      protocol: TCP
      nodePort: {{ .Values.service.agent.nodePort }}
      name: {{.Values.service.agent.targetPort}}
  selector:
    {{- include "jenkinsci.selectorLabels" . | nindent 4 }}
