apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jenkinsci.serviceAccountName" . }}
  namespace: {{ template "jenkinsci.namespace" . }}
  labels:
    {{- include "jenkinsci.labels" . | nindent 4 }}